### ISSUE TITLE
lts-latest installs non-lts version

### ISSUE THREAD

**Issue by rotu** [moonrepo/node-plugin#24]
`proto install node lts-latest` installs the non-LTS version 21.4.0.

(the correct syntax is `proto install node stable`)

Perhaps `lts` should be an alias for `stable`.
Perhaps `proto list-remote node` should show the named aliases.

**Comment by milesj** [comment]
It's because `lts-latest` isn't a supported value. Is enough to add here: https://github.com/moonrepo/node-plugin/blob/master/crates/node/src/proto.rs#L107

**Comment by rotu** [comment]
> It's because `lts-latest` isn't a supported value

I might agree with you if there were help text showing which values are "supported" 😉.

Ah I didn't even realize that `lts-*` and `lts/*` are existing aliases for `stable`. I'd probably make that *just* `lts` so the user doesn't have to quote to prevent glob-expansion. Or ditch it.

At any rate, it should probably reject things like `lts-19` as well. I might even scrap the `lts-...` prefix scheme altogether; installing via the named lts like `proto install node iron` is quite fancy enough!

**Comment by milesj** [comment]
These aliases are actually in `~/.proto/tools/node/remote-versions.json`. I'll bubble up the info.

<img width="321" alt="Screenshot 2023-12-06 at 9 20 01 PM" src="https://github.com/moonrepo/node-plugin/assets/143744/a5f5cf26-56ba-4111-8507-d878e8aff20e">

**Comment by rotu** [comment]
I'm not sure what I'm looking at, but I'm guessing that a preview of a future version of `proto tool info node` or `proto list-remote node`? If so, SWEET! Looks awesome!

**Comment by milesj** [comment]
Yup, both. We have the info, so added: https://github.com/moonrepo/proto/pull/323

I also updated this plugin with these OP aliases.
