### ISSUE TITLE
Installing yarn berry does not work

### ISSUE THREAD

**Issue by niieani** [moonrepo/node-plugin#6]
Hi!

I'm trying to use proto to install yarn berry without much success :/

```
❯ proto install yarn 4.0.0-rc.49
Error: proto::version::unresolved

  × Failed to resolve a semantic version for 4.0.0-rc.49.

❯ proto install yarn latest
Error: proto::version::unresolved

  × Failed to resolve a semantic version for ~3.
```

Am I doing something wrong?

I tried this manually, because when I use `moon` and configure it to use `yarn` with version `4.0.0-rc.49` it instead uses `proto` to download yarn v1 for some reason.

So it seems like there is some issue with `proto` itself.

<details>
<summary>See output with tracing</summary>
<pre>
❯ proto install yarn 4.0.0-rc.49 --log trace
[DEBUG 2023-08-21 23:26:37] proto::tools:run  Traversing upwards to find a configured plugin  tool="yarn"
[TRACE 23:26:37] warpgate::loader:run  Creating plugin loader  cache_dir="/Users/bbrzoska/.proto/plugins"
[TRACE 23:26:37] warpgate::loader:run  Loading plugin yarn  plugin="yarn" locator="source:https://github.com/moonrepo/node-plugin/releases/latest/download/node_depman_plugin.wasm"
[TRACE 23:26:37] starbase_utils::fs:run  Reading file metadata  file="/Users/bbrzoska/.proto/plugins/yarn-latest-97c64e7ac31561f08ea3e9fe3a56855085c776590737c26265a94760e5551ae7.wasm"
[TRACE 23:26:37] warpgate::loader:run  Plugin already downloaded and cached  plugin="yarn" path="/Users/bbrzoska/.proto/plugins/yarn-latest-97c64e7ac31561f08ea3e9fe3a56855085c776590737c26265a94760e5551ae7.wasm"
[DEBUG 23:26:37] proto::tools:run  Loading WASM plugin  source="/Users/bbrzoska/.proto/plugins/yarn-latest-97c64e7ac31561f08ea3e9fe3a56855085c776590737c26265a94760e5551ae7.wasm"
[DEBUG 23:26:37] proto_core::tool_manifest:run:load  Loading manifest.json  file="/Users/bbrzoska/.proto/tools/yarn/manifest.json"
[TRACE 23:26:37] starbase_utils::fs:run:load  Reading file with shared lock  file="/Users/bbrzoska/.proto/tools/yarn/manifest.json"
[TRACE 23:26:37] starbase_utils::fs:run:load  Opening file  file="/Users/bbrzoska/.proto/tools/yarn/manifest.json"
[TRACE 23:26:37] warpgate::plugin:run  Called plugin function register_tool  plugin="yarn" func="register_tool" input={"id":"yarn","env":{"arch":"arm64","id":"yarn","os":"macos","vars":{},"version":"latest"},"home_dir":"/home/"} output={"env_vars":["PROTO_NODE_VERSION"],"inventory":{"disable_progress_bars":false},"name":"yarn","type_of":"DependencyManager"}
[DEBUG 23:26:37] proto_core::tool:run  Resolving a semantic version  tool="yarn" initial_version="4.0.0-rc.49"
[DEBUG 23:26:37] proto_core::tool:run  Loading available versions  tool="yarn"
[TRACE 23:26:37] starbase_utils::fs:run  Reading file metadata  file="/Users/bbrzoska/.proto/tools/yarn/remote-versions.json"
[DEBUG 23:26:37] proto_core::tool:run  Loading from local cache  tool="yarn" cache="/Users/bbrzoska/.proto/tools/yarn/remote-versions.json"
[TRACE 23:26:37] starbase_utils::fs:run  Reading file with shared lock  file="/Users/bbrzoska/.proto/tools/yarn/remote-versions.json"
[TRACE 23:26:37] starbase_utils::fs:run  Opening file  file="/Users/bbrzoska/.proto/tools/yarn/remote-versions.json"
[TRACE 23:26:37] starbase_utils::fs:run  Writing file with exclusive lock  file="/Users/bbrzoska/.proto/tools/yarn/remote-versions.json"
[TRACE 23:26:37] warpgate::plugin:run  Called plugin function resolve_version  plugin="yarn" func="resolve_version" input={"initial":"4.0.0-rc.49","env":{"arch":"arm64","id":"yarn","os":"macos","vars":{},"version":"latest"}} output={}
Error: proto::version::unresolved

  × Failed to resolve a semantic version for 4.0.0-rc.49.

</pre>
</details>

**Comment by milesj** [comment]
@niieani Does 4.0.0-rc.49 show up when you do `proto list-remote node`?

**Comment by milesj** [comment]
Ok yeah, reproduced it locally. Will have a fix soon.

Edit: This works in the 0.15 branch which will land in a few days.

**Comment by niieani** [comment]
Thanks @milesj!

**Comment by milesj** [comment]
@niieani  0.15 has been released, let me know if that works.

**Comment by niieani** [comment]
It does, thanks!
